### ISSUE TITLE
다크모드를 쿠키로 넘기는 건 어떠신가요?

### ISSUE THREAD

**Issue by Exist95** [Exist95/Front-interview#1]
DB에 boolean으로 다크모드 상태를 저장하는 걸로 이야기가 됐는데, 크롬에서 해당 계정의 쿠키나 사이트 데이터를 초기화하면 다크모드가 풀리더라구요. 
OAuth 만료일에 맞춰서 자동으로 풀리게 구현해도 될 거 같아요!! 
어떠실까요?

**Comment by hongdahee** [comment]
말씀해 주신대로 전역 상태로 관리하는 걸로 하는 게 좋을 거 같아요!
