### ISSUE TITLE
모달 관련 이슈

### ISSUE THREAD

**Issue by Exist95** [Exist95/Front-interview#32]
회원탈퇴, 로그아웃, 비밀번호 변경 시 재확인을 요청하는 모달을 구현하면 좋을 거 같아요!

**Comment by hongdahee** [comment]
좋습니다!👍🏻

**Comment by Exist95** [comment]
모달 구현 시, absolute를 사용해야 할 텐데, 각자 휴대폰에서 어떻게 보이는지 확인해 봐야 할 것 같아요~
