### ISSUE TITLE
하단 탭 로고 이슈

### ISSUE THREAD

**Issue by hongdahee** [Exist95/Front-interview#9]
하단 탭 구현을 완료했는데 이 라이브러리를 사용하면 탭 마다 이동할 컴포넌트를 전달해야 해서 로고 탭은 넣지 못할 거 같습니다. 로고 탭을 빼거나, 로고 탭을 눌렀을 때 이동할 페이지가 있어야 할 거 같습니다. 일단 탭을 빼고 pr 올렸는데 좋은 의견 있으시면 알려 주세요!
![KakaoTalk_Photo_2023-01-21-23-55-12](https://user-images.githubusercontent.com/107875003/213872539-88187e03-892e-446a-a3cb-77345306d9d3.jpeg)

**Comment by Exist95** [comment]
그럼 로고를 프로필 사진이랑 같은 레벨에 두면 어떨까요??

**Comment by hongdahee** [comment]
그것도 좋네요 헤더 왼쪽에 둘게요~
